### ISSUE TITLE
BUG: Pindel doesn't support underscores in PATIENT

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#81]
```sh
$ lg3 --version
2018-10-08

$ cat _Pindel_Patient157_t10_underscore.out
[...]
Input:
- datafile=Patient157_t10_underscore.indels
- interval=/cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel2/resources/All_exome_targets.extended_200bp.bed
data  6294
filterdata  26
pat_list  ['Patient157']
p  Patient157
pat_data  26
26
[2018-10-11 16:15:50 PDT] END: /cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel2/scripts/pindel_filter.sh
[...]

$ tail -20 _Pindel_Patient157_t10_underscore.err
NOTICE: Reading gene annotation from /cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel2/AnnoVar/hg19db/hg19_refGene.txt ... Done with 38546 transcripts (including 6077 without coding sequence annotation) for 23241 unique genes
NOTICE: Reading FASTA sequences from /cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel2/AnnoVar/hg19db/hg19_refGeneMrna.fa ... Done with 1 sequences
NOTICE: Finished gene-based annotation on 24 genetic variants in Patient157_t10_underscore.indels.tmp3
NOTICE: Output files were written to Patient157_t10_underscore.indels.filter.intersect.anno.variant_function, Patient157_t10_underscore.indels.filter.intersect.anno.exonic_variant_function
Traceback (most recent call last):
  File "/cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel2/scripts/pindel_annotate_normal_coverage.py", line 123, in <module>
    pindel_annotate_normal_coverage(sys.argv[1], sys.argv[2].strip())
  File "/cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel2/scripts/pindel_annotate_normal_coverage.py", line 35, in pindel_annotate_normal_coverage
    cfg_file = open('../' + p + '.pindel.cfg')
IOError: [Errno 2] No such file or directory: '../Patient157.pindel.cfg'
```

I'll fix.

**Comment by HenrikBengtsson** [comment]
Not certain, but I suspect this comes from [scripts/pindel_filter.py](https://github.com/UCSF-Costello-Lab/LG3_Pipeline/blob/master/scripts/pindel_filter.py#L73-L77):
```py
    pp = l[tum].split("_")
    if (pp[0] not in pat_list): pat_list.append(pp[0])
    l.append(pp[0])
    l.append("_".join(pp[1:len(pp)]))
    filterdata.append('\t'.join(l))
```

**Comment by HenrikBengtsson** [comment]
I've nailed down the code where/why the Pindel step does not support Patient IDs with underscores, cf. commit 1ccfe4c9.  I've added a source code comment and NEWS entry about it.

It looks a little bit risky trying to fix it; there's a lot of split by `_` and then rejoin which is based on assumptions of a single underscore (I think).  

I propose that we document this as "known issue" and add assertions against underscores in `PATIENT` wherever possible.  We can later try to fix it, if really needed, but at least we protect against it for now.

**Comment by HenrikBengtsson** [comment]
I've now added protection against this through the code, e.g.
```sh
lg3 test setup
*** Setup
[OK] LG3_HOME: /home/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel
[OK] R packages: 'RColorBrewer'
[OK] Run scripts: _run_Align_gz
[...]
[OK] PROJECT: LG3
[ERROR] PATIENT: Patient157_t10_underscore (must not contain underscores)
[...]
```
and
```sh
./_run_Pindel 
[2018-10-16 13:14:20 PDT] BEGIN: ./_run_Pindel
Call: ./_run_Pindel
Script: ./_run_Pindel
Arguments: 
Input:
- LG3_HOME=/cbc2/data2/henrik/repositories/UCSF-CostelloLab/LG3_Pipeline-devel
- LG3_INPUT_ROOT=output
- LG3_OUTPUT_ROOT=/cbc/henrik/LG3_Pipeline_tests/test-devel-20181011a-t10_underscores/output
- EMAIL=henrik.bengtsson@gmail.com
- PATIENT=Patient157_t10_underscore
- PROJECT=LG3
- CONV=patient_ID_conversions.tsv
ERROR: 'PATIENT' must not contain underscores: Patient157_t10_underscore
```
