### ISSUE TITLE
ROBUSTNESS: Quote also `-I <file>` or `INPUT=<file>` options

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-Costello-Lab/LG3_Pipeline#9]
Follow up from https://github.com/UCSF-Costello-Lab/LG3_Pipeline/issues/7#issuecomment-417816094:

```sh
$ grep -A 4 -B 1 -iF 'INPUTS=' scripts/*.sh
scripts/Germline.sh-## Construct string with one or more '-I <bam>' elements
scripts/Germline.sh:INPUTS=$(for i in ${bamdir}/*.bam
scripts/Germline.sh-do
scripts/Germline.sh-	echo -n "-I $i "
scripts/Germline.sh-done)
scripts/Germline.sh-echo "$INPUTS"
--
scripts/Merge_QC.sh-## Construct string with one or more '-I <bam>' elements
scripts/Merge_QC.sh:inputs=$(echo "$bamfiles" | awk -F ":" '{OFS=" "} {for (i=1; i<=NF; i++) printf "INPUT="$i" "}')
scripts/Merge_QC.sh-
scripts/Merge_QC.sh-echo "[Merge] Merge BAM files..."
scripts/Merge_QC.sh-# shellcheck disable=SC2086
scripts/Merge_QC.sh-# Comment: Because how 'inputs' is created and used below
--
scripts/Merge.sh-## Construct string with one or more '-I <bam>' elements
scripts/Merge.sh:inputs=$(echo "$bamfiles" | awk -F ":" '{OFS=" "} {for (i=1; i<=NF; i++) printf "INPUT="$i" "}')
scripts/Merge.sh-
scripts/Merge.sh-echo "[Merge] Merge BAM files..."
scripts/Merge.sh-# shellcheck disable=SC2086
scripts/Merge.sh-# Comment: Because how 'inputs' is created and used below
--
scripts/Recal_bigmem.sh-## Construct string with one or more '-I <bam>' elements
scripts/Recal_bigmem.sh:inputs=$(echo "$bamfiles" | awk -F ":" '{OFS=" "} {for (i=1; i<=NF; i++) printf "INPUT="$i" "}')
scripts/Recal_bigmem.sh-
scripts/Recal_bigmem.sh-echo "[Recal] Merge BAM files..."
scripts/Recal_bigmem.sh-# shellcheck disable=SC2086
scripts/Recal_bigmem.sh-# Comment: Because how 'inputs' is created and used below
--
scripts/Recal_pass2.sh-## Construct string with one or more '-I <bam>' elements
scripts/Recal_pass2.sh:inputs=$(echo "$bamfiles" | awk -F ":" '{OFS=" "} {for (i=1; i<=NF; i++) printf "INPUT="$i" "}')
scripts/Recal_pass2.sh-
scripts/Recal_pass2.sh-echo "[Recal_pass2] Merge BAM files..."
scripts/Recal_pass2.sh-# shellcheck disable=SC2086
scripts/Recal_pass2.sh-# Comment: Because how 'inputs' is created and used below
--
scripts/Recal.sh-## Construct string with one or more '-I <bam>' elements
scripts/Recal.sh:inputs=$(echo "$bamfiles" | awk -F ":" '{OFS=" "} {for (i=1; i<=NF; i++) printf "INPUT="$i" "}')
scripts/Recal.sh-
scripts/Recal.sh-echo "[Recal] Merge BAM files..."
scripts/Recal.sh-# shellcheck disable=SC2086
scripts/Recal.sh-# Comment: Because how 'inputs' is created and used below
--
scripts/UG.sh-## Construct string with one or more '-I <bam>' elements
scripts/UG.sh:INPUTS=$(echo "$BAMS" | awk -F ":" '{OFS=" "} {for (i=1; i<=NF; i++) printf "-I "$i" "}')
scripts/UG.sh-echo "[$PROG] Inputs = $INPUTS"
scripts/UG.sh-
scripts/UG.sh-	echo "[$PROG] Running Unified Genotyper SNP calling ..."
scripts/UG.sh-	# shellcheck disable=SC2086
```

**Comment by HenrikBengtsson** [comment]
So, it looks like Picard does not like quoting `INPUT="/path/to/file.bam"` (although it's ok with `OUTPUT="..."`).  If using quotes, it looks for the file at `${PWD}"/path/to/file.bam"`, e.g.

```sh
[Recal] Recalibration Group: Patient157t10                                                                        
[Recal] Exome:/cbc/henrik/LG3_Pipeline_tests/testing-devel-20181026a/output/LG3/exomes/Z00599t10/Z00599t10.trim.bwa.sorted.bam           
[Recal] Exome:/cbc/henrik/LG3_Pipeline_tests/testing-devel-20181026a/output/LG3/exomes/Z00600t10/Z00600t10.trim.bwa.sorted.bam
[Recal] Exome:/cbc/henrik/LG3_Pipeline_tests/testing-devel-20181026a/output/LG3/exomes/Z00601t10/Z00601t10.trim.bwa.sorted.bam           
------------------------------------------------------             
inputs=INPUT="/cbc/henrik/LG3_Pipeline_tests/testing-devel-20181026a/output/LG3/exomes/Z00599t10/Z00599t10.trim.bwa.sorted.bam" INPUT="/c
bc/henrik/LG3_Pipeline_tests/testing-devel-20181026a/output/LG3/exomes/Z00600t10/Z00600t10.trim.bwa.sorted.bam" INPUT="/cbc/henrik/LG3_Pi
peline_tests/testing-devel-20181026a/output/LG3/exomes/Z00601t10/Z00601t10.trim.bwa.sorted.bam"                                          
                                
[Recal] Merge BAM files...                                                                                                               
Exception in thread "main" net.sf.picard.PicardException: Cannot read non-existent file: /scratch/henrik/1232681.cclc01.som.ucsf.edu/Pati
ent157t10/"/cbc/henrik/LG3_Pipeline_tests/testing-devel-20181026a/output/LG3/exomes/Z00599t10/Z00599t10.trim.bwa.sorted.bam"             
        at net.sf.picard.io.IoUtil.assertFileIsReadable(IoUtil.java:55)                                               
        at net.sf.picard.sam.MergeSamFiles.doWork(MergeSamFiles.java:99)                                                                 
        at net.sf.picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:177)                         
        at net.sf.picard.sam.MergeSamFiles.main(MergeSamFiles.java:84)                               
```

**Comment by HenrikBengtsson** [comment]
Hmm... same with GATK `-I="file.bam"`;
```
##### ERROR MESSAGE: Invalid command line: The GATK reads argument (-I, --input_file) supports only BAM files with the .bam extension and lists of BAM files with the .list extension, but the file "/cbc/henrik/LG3_Pipeline_tests/testing-devel-20181026a/output/LG3/exomes_recal/Patient157t10/Z00599t10.bwa.realigned.rmDups.recal.bam" has neither extension.  Please ensure that your BAM file or list of BAM files is in the correct format, update the extension, and try again.
```

So, cannot use `-I "path/to/file.bam"` either - reverting back to `-I path/to/file.bam`.  Interesting and odd.

**Comment by HenrikBengtsson** [comment]
I think I've undone any of these develop edits now.  What's left is the following NEWS entry:
```
### KNOWN ISSUES

* It appears not to be possible to quote `INPUT` filenames for Picard, i.e.
  we cannot use `INPUT="<file>"` but have to stick with `INPUT=<file>`.
  This means that those input file names must not have spaces.  GATK has
  the same limitation on its `-I <file>` option.
```

**Comment by ivan108** [comment]
I am still puzzled with this issue, because it seemed to work with Recal scripts, both with GATK and Picard??

**Comment by HenrikBengtsson** [comment]
It actually failed for `scripts/Recal*.sh` scripts as well. I had to roll it back for those too.

Having said that, yes, "it should work".  This could be related with how we build a string `inputs` consisting of multiple `INPUT="foo.bam"` and then passing it as `${inputs}`.  It might be that building a proper Bash array would work.  I need to think more about it.
